@startuml
!include style.puml
autoactivate on

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":CommandReceivedPanel" as CommandReceivedPanel UI_COLOR
end box

[-> MainWindow : executeCommand("course delete")
activate MainWindow

MainWindow -> MainWindow : refreshCommandReceived("course delete")

MainWindow -> CommandReceivedPanel : setCommandReceived("course delete")
activate CommandReceivedPanel

return
deactivate
deactivate

[<-- MainWindow
deactivate MainWindow
@enduml

