@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "r:CourseAchieveCommand" as CourseAchieveCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":CourseBook" as CourseBook MODEL_COLOR
participant ":CourseInfo" as CourseInfo MODEL_COLOR
end box

[-> CourseAchieveCommand : execute()
activate CourseAchieveCommand

CourseAchieveCommand -> Model : getCourseInfo()
activate Model

Model -> CourseBook : getCourseInfo()
activate CourseBook

CourseBook --> Model
deactivate CourseBook

Model --> CourseAchieveCommand
deactivate Model

CourseAchieveCommand --> CourseInfo : computeEstimatedCap(Course info, Cap)
activate CourseInfo

CourseInfo --> CourseInfo : getSemesters()
activate CourseInfo
CourseInfo --> CourseInfo : Semesters
deactivate CourseInfo
CourseInfo --> CourseInfo : getCap()
activate CourseInfo
CourseInfo --> CourseInfo : Cap
deactivate CourseInfo

CourseInfo --> CourseAchieveCommand
deactivate CourseInfo

create CommandResult
CourseAchieveCommand --> CommandResult
activate CommandResult
CommandResult --> CourseAchieveCommand
deactivate CommandResult

[<--CourseAchieveCommand : result
deactivate CourseAchieveCommand
@enduml
