@startuml
class CourseInfo {
    +getName()
    +getCap()
    +getCredits()
    +getSemesters()
    +{static} computeCredits(List<Requirement>)
    +{static} computeCap(List<ModuleList>, List<Requirement>)
    +{static} computeSemesters(Semesters, List<Module>)
    +equals()
    +hashCode()
    +toString()
}
class Name {}

CourseInfo o--> "1" Name
CourseInfo o--> "1" Cap
CourseInfo o--> "1" Credits
CourseInfo o--> "1" Semesters

@enduml
