@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyCourseBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class CourseBook
Class ReadOnlyCourseBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Module {
Class Module
Class Credits
Class Description
Class Grade
Class Memo
Class ModuleCode
Class Semester
Class Title
Class UniqueModuleList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

CourseBook .up.|> ReadOnlyCourseBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" CourseBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

CourseBook *--> "1" UniqueModuleList
UniqueModuleList o--> "*" Module
Module *--> ModuleCode
Module *--> Title
Module *--> Credits
Module *--> Description
Module *--> Semester
Module *--> Grade

Module *--> Memo
Module *--> "*" Tag

ModuleCode -[hidden]right-> Title
Title -[hidden]right-> Credits
Credits -[hidden]right-> Grade
Grade -[hidden]right-> Semester
Semester -[hidden]right-> Description
Description -[hidden]right-> Memo

ModelManager -->"1" Module : filtered list
@enduml
