@startuml
class Requirement {
    +isFulfilled()
    +equals()
    +hashCode()
    +toString()
}
class Name {}
class Credits {}
class UniqueModuleList {}

Requirement *-- "1" Name
Requirement *-- "1" Credits
Requirement *-- "1" UniqueModuleList
@enduml
