@startuml
!include style.puml

skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "module add n/CS2103T -a"

package States <<rectangle>> {
    class State1 as "__cb0:CourseBook__"
    class State2 as "__cb1:CourseBook__"
    class State3 as "__cb2:CourseBook__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

hide State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State2
@enduml
