@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CourseBookParser" as CourseBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedCourseBook" as VersionedCourseBook MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> CourseBookParser : parseCommand(undo)
activate CourseBookParser

create UndoCommand
CourseBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> CourseBookParser
deactivate UndoCommandCourse

CourseBookParser --> LogicManager : u
deactivate CourseBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoCourseBook()
activate Model

Model -> VersionedCourseBook : undo()
activate VersionedCourseBook

VersionedCourseBook -> VersionedCourseBook :resetData(ReadOnlyCourseBook)
VersionedCourseBook --> Model :
deactivate VersionedCourseBook

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
