= Wayne Wee - Project Portfolio

:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: iGrad

== Overview

iGrad is a desktop module management and graduation tracking application. The user interacts with it using a CLI, and it has a GUI created with JavaFX, FXML and CSS.

== Summary of contributions

* *Major enhancement*: added *the ability to add, edit and delete modules*
** _What it does_: allows the user to add, edit and delete modules.
** _Justification_: This feature is crucial in allowing the application to run as intended. A user can add a module with
a module code, title and module credits. They can also tag the module with a semester.
** _Highlights_: This feature was done mainly by refactoring existing code.
** _Credits_: The original AB3 for laying down most of the code.

* *Major enhancement*: added *the ability to add modules based on information from NUSMods*
** _What it does_: allows the user to add multiple modules at one time based on information from NUSMods.
** _Justification_: This feature improves the product significantly because a user can make mistakes
while typing in module information and getting the information directly from NUSMods solves this problem. In addition, the user is now able to add up to 10 modules
at a time without having to specify more details other than the module code. This speeds things up significantly from having not only to key in modules one by one, but
also to fill up all the details. Finally, this feature also allows to check for module prerequisites and preclusions that the user might not be aware of.
** _Highlights_: The only HTTP request made in the whole application.
** _Credits_: NUSMods (for making all the data public and free to use)

* *Major enhancement*: added *the ability to undo a previous command*
** _What it does_: allows the user to undo a previous command.
** _Justification_: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** _Highlights_: Had to choose between different implementations of this command.

* *Major enhancement*: added *the ability to filter modules*
** _What it does_: allows the user to filter modules based on certain parameters.
** _Justification_: This feature improves the product significantly because a user can face difficulty when attempting to look for a certain module.
** _Highlights_: Added the option to chain parameters by different logical operators, allowing users maximum flexibility

* *Major enhancement*: added and designed *a clean and user-friendly Graphical User Interface (GUI)*
** _What it does_: improves the user experience greatly
** _Justification_: This feature improves the product significantly because no matter how well an application functions, nothing matters if
the user experience is poor.
** _Highlights_: Inclusion of an  animal guide, displaying inspirational quotes and a progress bar.
** _Credits_: https://github.com/dargohzy[Daryl] for the first few iterations and implementations of the GUI, help panel and image
designs.

* *Major enhancement*: added *the ability to export module data*
** _What it does_: exports modules tagged with a semester to a .csv file titled study_plan.csv
** _Justification_: This feature improves the product significantly because it saves the user a lot of time should they wish to
copy the data somewhere else. The file generated by this command can be used to submit to school administration
for exchange programme, leave of absence and internship applications.
** _Highlights_: Only command to write to a .csv file.

* *Minor enhancement*: did the logic and interface to select an animal guide

* *Minor enhancement*: added a quote generator that displays a random quote each time a command is entered

* *Code contributed*: [https://github.com/AY1920S2-CS2103T-F09-3/main/tree/master/src/main[Functional code]] [https://github.com/AY1920S2-CS2103T-F09-3/main/tree/master/src/test[Test code]]
* *Other contributions*:

** Project presentation:
*** Designed the theme used for the project presentation
** Bug fixes:
*** Helped fix some bugs (https://github.com/AY1920S2-CS2103T-F09-3/main/pull/301[#301], https://github.com/AY1920S2-CS2103T-F09-3/main/pull/269[#269], https://github.com/AY1920S2-CS2103T-F09-3/main/pull/185[#185], https://github.com/AY1920S2-CS2103T-F09-3/main/pull/158[#158], https://github.com/AY1920S2-CS2103T-F09-3/main/pull/108[#108], https://github.com/AY1920S2-CS2103T-F09-3/main/pull/96[#96], https://github.com/AY1920S2-CS2103T-F09-3/main/pull/95[#95])
*** Removed unnecessary fields (https://github.com/AY1920S2-CS2103T-F09-3/main/pull/284[#284], https://github.com/AY1920S2-CS2103T-F09-3/main/pull/210[#210)
** Community:
*** Reported bugs and suggestions for other teams in the class

<<<

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=wayne-ug]

<<<

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=wayne-ug]

