@startuml
start
:User executes\nRequirement Add command;

if () then (invalid or missing prefixes\n       and/or parameters)
    :iGrad displays an error message\nand asks user to enter the\nnecessary parameters;
else (  valid prefixes\nand parameters)
    :Requirement is added;
endif
stop
@enduml
