Section by: https://github.com/waynewee[Wayne] & https://github.com/yjskrs[Yijie]

This segment contains a list of commands with examples that you can use to make full use of iGrad.

Take note of the following when using our commands:

WARNING: Commands with fields wrapped within square brackets (i.e. []) require at least one of these fields to be specified
when using the command.
This means that you need just specify one of these fields while others may be optional based on your usage.


==== help

Displays a help message to the user. Lists all possible commands
and provides a link to the user guide online.

Command Format

----
help
----

Expected Outcome
[NOTE]
A popup for the list of all commands as well as the link to the user guide is shown.
`INSERT POPUP PHOTO`

'''

==== course

Add, edit or delete your course. Find out how much CAP you need to maintain
each semester to achieve your desired CAP.

Command Format

----
course add n/COURSE_NAME

course edit [n/COURSE_NAME] [u/MCs]

course delete n/COURSE_NAME

course achieve c/DESIRED_CAP s/SEMESTERS_LEFT
----

Command Sample

Creating a course named "Computer Science"
----
course add n/Computer Science
----


Renaming your current course to "Information Systems"
----
course edit n/Information Systems
----

Removing your current course
----
course delete
----

Calculating the average grade needed to achieve a CAP of 4.50 with
2 semesters left
----
course achieve c/4.50 s/2
----

Constraints
[WARNING]
====
1. `(all)`: You can only have at most one course at any one time
2. `course delete`: Removing a course deletes all data from the system (including modules, requirements, etc)
====

Expected Outcome
[NOTE]
You should be able to see the added and/or modified course name in the
top panel. For delete course, all data would be reset

'''

==== requirement

Add, edit or delete a graduation requirement.

Command Format

----
requirement add n/REQUIREMENT_TITLE u/MCS_REQUIRED

requirement edit REQUIREMENT_CODE [n/NEW_REQUIREMENT_TITLE] [u/NEW_MCS_REQUIRED]

requirement delete REQUIREMENT_CODE

requirement assign REQUIREMENT_CODE [n/MODULE_CODE ...]
----

Command Sample

Adding a requirement named "Unrestricted Electives" which requires 32 MCs.
----
requirement add n/Unrestricted Electives u/32
----

Renaming requirement "Unrestricted Electives" to "Maths and Sciences", and changing the number of MCs required to 20.

----
requirement edit Unrestricted Electives n/Maths and Sciences u/32
----

Renaming requirement "Unrestricted Electives" to "Maths and Sciences".
----
requirement edit Unrestricted Electives n/Maths and Sciences
----

Changing number of required MCs for requirement "Unrestricted Electives" to 20.
----
requirement edit Unrestricted Electives u/20
----

Removing requirement named "Unrestricted Electives".
----
requirement delete Unrestricted Electives
----

Assigning modules to requirement.
----
requirement assign UE0 n/CS1101S n/CS1231S n/CS2030S n/CS2040S
----

Constraints
[WARNING]
====
1. None.
====

Expected Outcome
[NOTE]
You should be able to see the requirement created and/or edited in the main panel.

'''
